server:
  port: 8080
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:9000/office_core_db
    username: postgres
    password: postgres
  liquibase:
    change-log: classpath:db/changelog/changelog.yml
